# Generated by Django 3.0.9 on 2020-08-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=5000)),
                ('content_genre', models.CharField(choices=[('COMEDY', 'comedy'), ('FICTION', 'fiction'), ('HORROR', 'horror'), ('THRILLER', 'thriller'), ('ROMANTIC', 'romantic'), ('FAMILY', 'family'), ('LIFESTYLE', 'lifestyle'), ('GAMING', 'gaming'), ('KNOWLEDGE', 'knowledge')], max_length=10)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
